# Generated by Django 3.1.2 on 2020-10-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_gym_tag_trainer_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(null=True, to='accounts.Tag'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='tags',
            field=models.ManyToManyField(null=True, to='accounts.Tag'),
        ),
    ]
