# Generated by Django 3.1.2 on 2020-10-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201026_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Tag'),
        ),
    ]
