# Generated by Django 3.1.2 on 2020-10-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201027_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
