# Generated by Django 3.1.2 on 2020-10-30 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('visit_count', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='프로그램 등록일')),
                ('start_date', models.DateField(verbose_name='프로그램 시작일')),
                ('end_date', models.DateField(verbose_name='프로그램 종료일')),
                ('class_registration_start_day', models.DateTimeField(verbose_name='프로그램 수강신청 시작날짜')),
                ('class_registration_end_day', models.DateTimeField(verbose_name='프로그램 수강신청 종료날짜')),
                ('max_student', models.IntegerField()),
                ('tags', models.ManyToManyField(to='accounts.Tag')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='accounts.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('content', models.CharField(max_length=800)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainercomment', to='accounts.client')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainercomment', to='accounts.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('start_hour', models.DateTimeField()),
                ('end_hour', models.DateTimeField()),
                ('hour', models.IntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='api.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programpayment', to='accounts.client')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programpayment', to='api.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programdetail', to='accounts.client')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programdetail', to='api.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDayDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=800)),
                ('chulseok', models.CharField(max_length=100)),
                ('Program_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programdaydetail', to='api.programdetail')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('content', models.CharField(max_length=800)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programcomment', to='accounts.client')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programcomment', to='api.program')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programcomment', to='accounts.trainer')),
            ],
        ),
    ]
