# Generated by Django 3.1.2 on 2020-11-03 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=800)),
                ('visit_count', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(to='accounts.Tag')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='accounts.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programday', to='api.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_online_count', models.IntegerField()),
                ('max_offline_count', models.IntegerField()),
                ('now_online_count', models.IntegerField()),
                ('now_offline_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programrecord', to='accounts.client')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programrecord', to='api.program')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('content', models.CharField(max_length=800)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainercomment', to='accounts.client')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainercomment', to='accounts.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('start_hour', models.DateTimeField()),
                ('end_hour', models.DateTimeField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='api.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramRecordDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=800)),
                ('programRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programrecorddetail', to='api.programrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('online_count', models.IntegerField()),
                ('offline_count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programprice', to='api.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programpayment', to='accounts.client')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programpayment', to='api.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('content', models.CharField(max_length=100)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programholiday', to='api.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDayTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.DateTimeField()),
                ('end_hour', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ProgramDay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programdaytime', to='api.programday')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programdaytime', to='accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('content', models.CharField(max_length=800)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programcomment', to='accounts.client')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programcomment', to='api.program')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programcomment', to='accounts.trainer')),
            ],
        ),
    ]
