# Generated by Django 3.1.2 on 2020-10-24 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programcomment',
            name='class_registration_end_day',
            field=models.DateTimeField(default='2020-10-01', verbose_name='프로그램 수강신청 종료날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programcomment',
            name='class_registration_start_day',
            field=models.DateTimeField(default='2020-09-01', verbose_name='프로그램 수강신청 시작날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programcomment',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='프로그램 등록일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programcomment',
            name='end_date',
            field=models.DateField(default='2020-11-30', verbose_name='프로그램 종료일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programcomment',
            name='max_student',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programcomment',
            name='start_date',
            field=models.DateField(default='2020-10-25', verbose_name='프로그램 시작일'),
            preserve_default=False,
        ),
    ]
