# Generated by Django 3.1.2 on 2020-11-09 04:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='thumb_img',
            field=models.ImageField(upload_to=api.models.program_image_path),
        ),
    ]
