# Generated by Django 3.1.2 on 2020-11-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programreservationtime',
            name='end_hour',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='programreservationtime',
            name='start_hour',
            field=models.TimeField(),
        ),
    ]
