# Generated by Django 3.1.2 on 2020-11-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201109_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programschedule',
            name='end_hour',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='programschedule',
            name='start_hour',
            field=models.TimeField(),
        ),
    ]
