# Generated by Django 3.1.2 on 2020-11-11 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201111_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programschedule',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programschedule', to='api.program'),
        ),
        migrations.CreateModel(
            name='ProgramWebRtc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webrtcroomId', models.CharField(max_length=200)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programwebrtc', to='api.program')),
            ],
        ),
    ]
