# Generated by Django 3.1.2 on 2020-11-12 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('api', '0002_auto_20201112_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom', to='accounts.client')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom', to='api.program')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom', to='accounts.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('time', models.DateTimeField()),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatlog', to='api.chatroom')),
            ],
        ),
    ]
